version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=notpassword
      - POSTGRES_PORT=5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: django-admin startproject apiexample
    volumes:
      - ./apiexample/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    # environment:
    # TODO: REMOVE THESE FOR PRODUCTION BUILD
    #  - SUPERUSER_USERNAME=root
    #  - SUPERUSER_PASSWORD=CaptainCaplanCommonChord
